name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Go-CI
      uses: rkoCyrus/Go-CI@2.0.0

    - name: make all
      run:  make all -C Substring_c
      
